/* Financial decomposition visual. Endpoints and components are supplied by TradeEngine. */
(function(root){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=(v,d=2)=>Number(v).toLocaleString('fa-IR',{maximumFractionDigits:d});
const money=v=>{if(!Number.isFinite(v))return 'قابل تعیین نیست';const a=Math.abs(v),scale=a>=1e12?1e12:a>=1e9?1e9:a>=1e6?1e6:1;return '\u2066'+(v<0?'−':'')+nf(a/scale,scale===1?(a<.01?8:2):3)+'\u2069 '+(scale===1e12?'تریلیون ':scale===1e9?'میلیارد ':scale===1e6?'میلیون ':'')+'تومان';};
const exact=v=>'\u2066'+(v<0?'−':'')+nf(Math.abs(v),Math.abs(v)<1?8:2)+'\u2069 تومان';
function render(r){
 if(!r?.economics)return '<p class="empty-state" role="status">پس از تکمیل قرارداد، ساختار اقتصاد معامله نمایش داده می‌شود.</p>';
 const e=r.economics,check=e.revenue-e.purchase-e.operations-e.financing-e.risk-e.other-e.profit;
 if(!Object.values(e).every(x=>x===null||Number.isFinite(x))||Math.abs(check)>e.tolerance||Math.abs(e.reconciliationDifference)>e.tolerance)return '<p role="alert" class="field-error">اجزای اقتصاد معامله تطبیق ندارند؛ نمودار قابل ارائه نیست.</p>';
 const parts=[{label:'عملیات',full:'هزینه‌های عملیات',value:e.operations,color:'#779b96'},{label:'تأمین مالی',full:'هزینه تأمین مالی و کارمزد',value:e.financing,color:'#b89554'},{label:'ریسک وصول',full:'هزینه ریسک وصول',value:e.risk,color:'#aa6877'},{label:'مالیات غیرقابل بازیافت',full:'مالیات غیرقابل بازیافت',value:e.other,color:'#807391'}].filter(x=>x.value!==0);
 const steps=[{label:'حاشیه اولیه',full:'فروش خالص منهای بهای خرید',value:r.gross,total:true,color:'#356985'},...parts.map(p=>({...p,value:-p.value})),{label:e.profit<0?'زیان معامله':'سود معامله',full:'سود یا زیان پس از هزینه‌ها',value:e.profit,total:true,color:e.profit<0?'#a13e4c':'#147467'},{label:'اثر زمان',full:'اثر ارزش زمانی و زمان‌بندی جریان نقدی',value:e.timeValueEffect,color:'#9a805a'},{label:'ارزش اقتصادی',full:'ارزش فعلی خالص ـ NPV',value:e.npv,total:true,color:e.npv<0?'#a13e4c':'#142d40'}];
 // Running values are coordinates of the bridge, not a second calculation of KPIs.
 let previous=0;steps.forEach(s=>{s.start=s.total?0:previous;s.end=s.total?s.value:previous+s.value;previous=s.end;});
 const all=steps.flatMap(s=>[s.start,s.end]),min=Math.min(0,...all),max=Math.max(0,...all),range=Math.max(max-min,1),W=960,H=365,L=78,R=26,T=70,B=86,plotH=H-T-B,gap=(W-L-R)/steps.length,bw=Math.min(68,gap*.56),y=v=>T+(max-v)/range*plotH;
 let svg='';[0,.5,1].forEach(t=>{const value=min+t*range,yy=y(value);svg+='<line x1="'+L+'" y1="'+yy+'" x2="'+(W-R)+'" y2="'+yy+'" stroke="#e2e9e6"/><text x="'+(L-10)+'" y="'+(yy+4)+'" text-anchor="end" fill="#526574" font-size="11">'+esc(money(value).replace(' تومان',''))+'</text>';});svg+='<line x1="'+L+'" y1="'+y(0)+'" x2="'+(W-R)+'" y2="'+y(0)+'" stroke="#8fa7a5" stroke-width="1.3"/>';
 steps.forEach((s,i)=>{const x=W-R-gap*(i+.5),top=y(Math.max(s.start,s.end)),height=Math.abs(y(s.start)-y(s.end)),small=height<2&&s.value!==0;const title=s.full+'؛ '+exact(s.value);if(i<steps.length-1)svg+='<line x1="'+(x-bw/2)+'" y1="'+y(s.end)+'" x2="'+(x-gap+bw/2)+'" y2="'+y(s.end)+'" stroke="#a6bab6" stroke-dasharray="4 4"/>';svg+='<g><title>'+esc(title)+'</title>'+(small?'<circle cx="'+x+'" cy="'+y(s.end)+'" r="3" fill="'+s.color+'"/>':'<rect x="'+(x-bw/2)+'" y="'+top+'" width="'+bw+'" height="'+Math.max(.6,height)+'" rx="3" fill="'+s.color+'"/>')+'<text x="'+x+'" y="'+(T-27)+'" text-anchor="middle" font-weight="600" fill="'+(s.value<0?'#a13e4c':'#193043')+'" font-size="12">'+esc(money(s.value).replace(' تومان',''))+'</text><text x="'+x+'" y="'+(H-B+31)+'" text-anchor="middle" fill="#193043" font-size="13">'+esc(s.label)+'</text></g>';});
 const mobileBridge='<div class="bridge-mobile">'+steps.map(s=>'<div class="mobile-bridge-step"><div><span>'+esc(s.label)+'</span><bdi>'+money(s.value)+'</bdi></div><div class="mobile-bridge-track"><i style="left:'+((0-min)/range*100)+'%"></i><span style="left:'+((Math.min(s.start,s.end)-min)/range*100)+'%;width:'+Math.max(.3,Math.abs(s.end-s.start)/range*100)+'%;background:'+s.color+'"></span></div></div>').join('')+'</div>';
 const exactRows=[['فروش خالص',e.revenue],['بهای خرید کالا',e.purchase],['حاشیه اولیه',r.gross],['هزینه عملیات',e.operations],['هزینه تأمین مالی و کارمزد',e.financing],['هزینه ریسک',e.risk],['مالیات غیرقابل بازیافت',e.other],['سود معامله',e.profit],['اثر ارزش زمانی پول',e.timeValueEffect],['ارزش فعلی خالص',e.npv]];
 const details=(title,list)=>'<details class="economics-detail"><summary>'+title+'</summary>'+list.map(x=>'<div><span>'+esc(x[0])+'</span><bdi>'+exact(x[1])+'</bdi></div>').join('')+'</details>';
 const insight=e.revenue<=0?'فروش خالص صفر است؛ حاشیه سود قابل محاسبه نیست.':e.profit<0?'هزینه‌های معامله از فروش بیشتر است؛ حاشیه سود '+nf(e.profitMargin*100)+'٪ است.':Math.abs(e.profitMargin*100)<.01?'حاشیه سود کمتر از ۰٫۰۱٪ است؛ معامله فضای بسیار کمی برای خطا دارد.':'از هر ۱۰۰ تومان فروش، '+nf(e.profitMargin*100)+' تومان سود باقی می‌ماند.';
 return '<div class="economics-v14"><p class="bridge-insight '+(e.profit<0?'negative':'')+'">'+insight+'</p><div class="waterfall-scroll"><svg class="value-waterfall" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="پل ارزش معامله؛ حاشیه اولیه، هزینه‌ها، سود، اثر زمان و NPV">'+svg+'</svg></div>'+mobileBridge+'<p class="waterfall-caption">حاشیه اولیه = فروش خالص − بهای خرید. طول ستون‌ها متناسب با مبلغ است؛ اجزای بسیار کوچک با نقطه مشخص می‌شوند. مبالغ دقیق در جزئیات قابل مشاهده‌اند.</p><div class="value-equation"><div><span>سود معامله</span><strong class="'+(e.profit<0?'negative':'positive')+'"><bdi>'+money(e.profit)+'</bdi></strong></div><i>+</i><div><span>اثر ارزش زمانی پول</span><strong class="'+(e.timeValueEffect<0?'negative':'positive')+'"><bdi>'+money(e.timeValueEffect)+'</bdi></strong></div><i>=</i><div><span>ارزش فعلی خالص</span><strong class="'+(e.npv<0?'negative':'positive')+'"><bdi>'+money(e.npv)+'</bdi></strong></div></div><details class="economics-detail"><summary>مبالغ دقیق و تطبیق اجزای اقتصاد معامله</summary><table class="bridge-exact-table"><thead><tr><th>جزء محاسبه</th><th>مبلغ به تومان</th></tr></thead><tbody>'+exactRows.map(x=>'<tr><td>'+x[0]+'</td><td><bdi>'+exact(x[1])+'</bdi></td></tr>').join('')+'</tbody></table><p>مالیات قابل بازیافت و وجه بلوکه هزینه نیستند؛ اثر زمان‌بندی آن‌ها در NPV لحاظ شده است. تطبیق اجزا با موتور محاسبات کنترل شده است.</p></details>'+details('ریز هزینه‌های عملیات',(r.operations||[]).map(x=>[x.label,x.amount]))+details('ریز هزینه مالی و کارمزد',(r.financeLegs||[]).flatMap(x=>[['اضافه‌قیمت '+({lc:'اعتبار اسنادی',cheque:'چک',boe:'برات'}[x.method]||x.method),x.financeMarkup],['کارمزد '+({lc:'اعتبار اسنادی',cheque:'چک',boe:'برات'}[x.method]||x.method),x.fee]]).concat((r.salesFinanceLegs||[]).filter(x=>x.feeDirection==='paid'&&x.fee).map(x=>['کارمزد پرداختی فروش',x.fee])))+(r.salesFeeIncome?details('کارمزد منظورشده در درآمد فروش',[['کارمزد دریافتی فروش',r.salesFeeIncome]]):'')+(r.warnings?.length?'<details class="economics-detail"><summary>فرض‌ها و محدودیت‌های محاسبه</summary>'+r.warnings.map(w=>'<p>'+esc(w)+'</p>').join('')+'</details>':'')+'</div>';
}
root.EconomicsView={render};
})(typeof window==='undefined'?globalThis:window);
