/* v14: presentation and navigation only. Financial values come from TradeEngine. */
(function(root){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={arrow:'<path d="M19 12H5m6-6-6 6 6 6"/>',deal:'<path d="M4 5h16v14H4zM8 9h8M8 13h5"/>',wallet:'<path d="M4 6h14v4h2v8H4zM15 10h5M16 14h1"/>',chart:'<path d="M4 4v16h16M8 15l4-5 4 2 4-7"/>',check:'<path d="m5 12 4 4L19 6"/>',layers:'<path d="m3 8 9-5 9 5-9 5zM3 12l9 5 9-5M3 16l9 5 9-5"/>',file:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/>',plus:'<path d="M12 5v14M5 12h14"/>'};
const icon=k=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[k]||icons.chart)+'</svg>';
const nf=(v,d=2)=>Number(v).toLocaleString('fa-IR',{maximumFractionDigits:d});
const pct=v=>v==null?'قابل محاسبه نیست':nf(v*100)+'٪';
function amount(v){if(!Number.isFinite(v))return {value:'—',unit:'',full:'قابل تعیین نیست'};const a=Math.abs(v),scale=a>=1e12?1e12:a>=1e9?1e9:a>=1e6?1e6:1;return {value:(v<0?'−':'')+nf(a/scale,scale===1?(a<.01?8:2):3),unit:(scale===1e12?'تریلیون ':scale===1e9?'میلیارد ':scale===1e6?'میلیون ':'')+'تومان',full:(v<0?'−':'')+nf(a,a<1?8:0)+' تومان'};}
function create(a){const $=a.el;let pageObserver,sectionObserver;
function setup(){
 document.body.classList.add('studio');if($('intro')&&!$('intro').classList.contains('is-hidden'))document.querySelector('.app').inert=true;
 const skip=document.createElement('a');skip.className='skip-link';skip.href='#mainContent';skip.textContent='رفتن به محتوای اصلی';document.body.prepend(skip);
 const shell=document.querySelector('.shell');shell.id='mainContent';shell.setAttribute('tabindex','-1');shell.setAttribute('role','main');
 const rail=document.createElement('aside');rail.className='workspace-rail';rail.setAttribute('aria-label','مسیر تحلیل معامله');rail.innerHTML='<div class="rail-brand">'+icon('chart')+'<span>میز معامله<small>تحلیل، ارزیابی و تصمیم</small></span></div><div class="rail-label">مسیر ارزیابی</div><div id="railSteps"></div><div class="rail-divider"></div><button class="rail-compare" type="button">'+icon('layers')+'<span>سناریوهای من</span><span id="railCount">۰</span></button><div class="rail-context"><span class="rail-label">معامله جاری</span><strong id="railCommodity">معامله جدید</strong><p id="railContext">اطلاعات قرارداد را وارد کنید.</p></div><div class="rail-foot"><span class="live-dot"></span>نسخه ۱۵<span>آتیه فولاد نقش جهان</span></div>';
 document.querySelector('.topbar').after(rail);rail.querySelector('#railSteps').appendChild($('stepper'));rail.querySelector('.rail-compare').onclick=()=>$('compareOpen').click();
 const typeCard=$('tradeTypeSegment').closest('.card');typeCard.classList.add('trade-type-card');
 $('commodity').closest('.card').querySelector('.card-head').hidden=true;const groups=[...$('quickPage').querySelectorAll('.entry-group')];groups.forEach((g,i)=>{g.classList.add('form-panel');g.dataset.number=nf(i+1,0);const head=g.querySelector('h2');head.insertAdjacentHTML('beforebegin','<span class="form-number">'+nf(i+1,0)+'</span>');});
 const priceGroup=groups[1];if(priceGroup){const fields=priceGroup.querySelector('.fields'),buy=document.createElement('div'),sell=document.createElement('div');buy.className='quote-side buy-side';sell.className='quote-side sell-side';buy.innerHTML='<div class="quote-side-heading"><span>خرید</span><small>مبلغ قرارداد با تأمین‌کننده</small></div><div class="fields"></div>';sell.innerHTML='<div class="quote-side-heading"><span>فروش</span><small>مبلغ قرارداد با مشتری</small></div><div class="fields"></div>';['purchasePrice','purchaseQuoteUnit','purchaseFx'].forEach(id=>buy.querySelector('.fields').appendChild($(id).closest('.field')));['salePrice','saleQuoteUnit','saleFx'].forEach(id=>sell.querySelector('.fields').appendChild($(id).closest('.field')));fields.className='quote-columns';fields.append(buy,sell);}
 const summary=$('quickPage').querySelector('.summary-row');summary.classList.add('contract-totals');summary.insertAdjacentHTML('beforebegin','<div class="totals-heading">خلاصه قرارداد <span>پیش از هزینه‌ها و شرایط پرداخت</span></div>');
 const cards=[...$('financePage').children].filter(n=>n.classList.contains('card')&&!n.hidden&&!n.classList.contains('tax-settings'));const contracts=document.createElement('div');contracts.className='contract-columns';cards[0].before(contracts);contracts.append(cards[0],cards[1]);cards[0].classList.add('purchase-panel');cards[1].classList.add('sales-panel');cards[2].classList.add('costs-panel');
 const lower=document.createElement('div');lower.className='finance-columns';contracts.after(lower);lower.append($('resourceInputs'),cards[2]);$('resourceInputs').classList.add('resource-panel');
 const advanced=document.createElement('div');advanced.className='optional-settings';advanced.innerHTML='<div class="optional-heading"><h2>فرض‌های تکمیلی</h2><p>برای قراردادهایی که به تنظیمات ریسک یا مالیات نیاز دارند.</p></div>';lower.after(advanced);advanced.append($('riskInputs'),$('financePage').querySelector('.tax-settings'));advanced.append($('entryAssumptions'));
 const tools=$('resultPage').querySelector('.cockpit-toolbar');tools.classList.add('report-toolbar');const exportButton=$('exportExcel');tools.querySelector('div').prepend(exportButton);$('resultKpis').after(tools);$('recalculate').textContent='به‌روزرسانی نتیجه';
 const hero=$('resultHero');hero.insertAdjacentHTML('afterbegin','<div class="decision-eyebrow"><span>'+icon('chart')+' جمع‌بندی تصمیم</span><span id="dealIdentity"></span></div>');
 hero.insertAdjacentHTML('beforeend','<div class="decision-next"><div><span>گام بعدی</span><strong id="nextActionText"></strong></div><button id="decisionNext" type="button" class="btn btn-primary">بررسی شرط انجام '+icon('arrow')+'</button></div>');
 $('decisionNext').onclick=()=>{const c=a.getLast(),v=root.TradeEngine.decision(c.d,c.r,c);const dest=v.action==='انجام معامله'?'analysis-1':v.action==='عدم انجام معامله'||v.action.includes('قیمت')?'analysis-1':'analysis-0';document.getElementById(dest).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});};
 const sections=[...$('resultPage').querySelectorAll('.cockpit-section')];sections.forEach(s=>{s.querySelector('.section-index').setAttribute('aria-hidden','true')});
 const readiness=$('facilityPanel').closest('.readiness-pane');readiness.querySelector('h3').textContent='منابع لازم برای اجرا';
 const gates=$('decisionGates');const det=document.createElement('details');det.className='gate-details';det.open=false;det.innerHTML='<summary>کنترل‌های تصمیم <span id="gateSummaryCompact"></span></summary>';gates.before(det);det.appendChild(gates);gates.closest('.readiness-pane').querySelector('h3').hidden=true;
 const sensitivity=$('sensitivityMatrix');const matrixDetails=document.createElement('details');matrixDetails.className='matrix-details';matrixDetails.open=true;matrixDetails.innerHTML='<summary>بررسی سناریوها در ماتریس <span>مقایسه هم‌زمان دو متغیر</span></summary>';sensitivity.before(matrixDetails);matrixDetails.append(sensitivity);
 const heading=$('resultPage').querySelector('.sens-card h2');heading.textContent='تاب‌آوری تصمیم';heading.parentElement.querySelector('p').textContent='چه تغییری نتیجه معامله را تهدید می‌کند؟';$('resultPage').querySelector('.sens-card .sensitivity-options').before($('sensitivityInsights'));const nav=$('resultPage').querySelector('.result-nav');nav.querySelectorAll('a').forEach((n,i)=>{n.innerHTML='<span>'+nf(i+1,0)+'</span>'+['آمادگی اجرا','مذاکره','اقتصاد معامله','جریان نقدی','حساسیت','ریسک'][i]});
 const cta=$('resultPage').querySelector('.compare-cta');cta.querySelector('.mini-title').textContent='این تصمیم را ثبت کنید';cta.querySelector('.mini-sub').textContent='سناریو را برای بازبینی و مقایسه نگه دارید؛ فایل معامله نیز قابل انتقال است.';$('addCompare').textContent='ثبت و مقایسه سناریو';
 $('comparePage').querySelector('.page-desc').textContent='اختلاف گزینه‌ها نسبت به مبنا؛ با امکان بازکردن، ویرایش و ساخت سناریوی مشابه.';
 document.querySelectorAll('.page-head').forEach((n,i)=>n.insertAdjacentHTML('afterbegin','<div class="page-eyebrow">'+['تعریف قرارداد','ساختار پول معامله','ارزیابی مدیریتی','سناریوهای تصمیم'][i]+'</div>'));
 $('quickPage').querySelector('.page-desc').textContent='قرارداد را همان‌طور که توافق شده وارد کنید؛ واحد، قیمت و زمان مبنای تحلیل خواهند بود.';
 document.querySelector('.footer-note').textContent='اطلاعات شما در همین مرورگر پردازش می‌شود.';
 // Preserve labels for both static and subsequently rendered fields.
 function labelFields(scope){scope.querySelectorAll('.field').forEach(f=>{const l=f.querySelector('label'),n=f.querySelector('input:not([type="hidden"]),select');if(l&&n&&n.id&&!l.htmlFor)l.htmlFor=n.id});}
 labelFields(document);document.querySelectorAll('.sens-matrix-wrap,.waterfall-scroll').forEach(n=>{n.tabIndex=0;n.setAttribute('role','region');n.setAttribute('aria-label',n.id==='sensitivityMatrix'?'ماتریس حساسیت؛ قابل پیمایش با صفحه‌کلید':'نمودار پل ارزش معامله')});let queued=false;pageObserver=new MutationObserver(m=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;labelFields(document);const active=document.querySelector('.page.active');document.body.dataset.page=active?.id||'quickPage';$('stepper').querySelectorAll('.step').forEach((s,i)=>{s.setAttribute('role','button');s.setAttribute('tabindex','0');s.setAttribute('aria-label',['مشخصات معامله','برنامه پرداخت و دریافت','نتایج معامله'][i]);s.setAttribute('aria-current',s.classList.contains('active')?'step':'false');if(!s.dataset.bound){s.dataset.bound='1';const activate=()=>{if(i===1&&a.state.step===1){$('nextBtn').click()}else if(i===2&&a.state.step<3){if(a.state.step===1){$('nextBtn').click();if(a.state.step!==2)return;}$('nextBtn').click()}else a.go(i+1)};s.onclick=activate;s.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}}}});if($('railCount').textContent!==$('compareCount').textContent)$('railCount').textContent=$('compareCount').textContent;});});pageObserver.observe(document.querySelector('.app'),{subtree:true,childList:true});
 document.addEventListener('input',e=>{if(e.target.closest('#quickPage'))updateContext()});document.addEventListener('change',e=>{if(e.target.closest('#quickPage'))updateContext()});
 let navQueued=false;const trackSection=()=>{if(!$('resultPage').classList.contains('active'))return;const threshold=document.querySelector('.topbar').getBoundingClientRect().bottom+nav.offsetHeight+24;let current=sections[0];sections.forEach(s=>{if(s.getBoundingClientRect().top<=threshold)current=s});nav.querySelectorAll('a').forEach(n=>{const yes=n.hash==='#'+current.id;n.classList.toggle('current',yes);if(yes)n.setAttribute('aria-current','location');else n.removeAttribute('aria-current')})};root.addEventListener('scroll',()=>{if(navQueued)return;navQueued=true;requestAnimationFrame(()=>{navQueued=false;trackSection()})},{passive:true});
 document.querySelector('.brand-title').textContent='تصمیم‌یار بازرگانی آتیه فولاد';document.querySelector('.brand-sub').textContent='گروه سرمایه‌گذاری آتیه فولاد نقش جهان';updateContext();
}
function updateContext(){if(!$('railCommodity'))return;$('railCommodity').textContent=$('commodity').value.trim()||'معامله جدید';const q=$('quantity').value,u=$('quantityUnit').selectedOptions[0]?.textContent||'';$('railContext').textContent=q?q+' '+u+' · '+($('holdingDays').value||'—')+' روز تا تحویل':'اطلاعات قرارداد را وارد کنید.';}
function renderCash(last){
 const r=last.r,d=last.d,box=$('cashFlowChart'),rows=r.daily;if(!rows.length){box.innerHTML='<p class="empty-state">جریان نقدی برای نمایش وجود ندارد.</p>';return;}
 const mobile=innerWidth<=680,W=mobile?Math.max(280,box.clientWidth):1000,H=mobile?330:350,pad={l:mobile?52:78,r:mobile?20:30,t:45,b:55},first=Math.min(0,rows[0].day),end=Math.max(first+1,rows.at(-1).day),limit=d.limits.cash;
 const vals=rows.flatMap(v=>[v.inflow,v.outflow,v.cum,-(v.intradayNeed||0)]);if(limit!=null)vals.push(-limit);const min=Math.min(0,...vals),max=Math.max(0,...vals),span=Math.max(1,max-min),top=max+span*.12,bottom=min-span*.12,scale=top-bottom;
 const x=day=>pad.l+(day-first)/(end-first)*(W-pad.l-pad.r),y=value=>pad.t+(top-value)/scale*(H-pad.t-pad.b),big=Math.max(Math.abs(top),Math.abs(bottom)),unit=big>=1e12?1e12:big>=1e9?1e9:big>=1e6?1e6:1,unitName=(unit===1e12?'تریلیون ':unit===1e9?'میلیارد ':unit===1e6?'میلیون ':'')+'تومان';
 const barW=Math.max(2,Math.min(mobile?17:28,(W-pad.l-pad.r)/Math.max(3,rows.length)/2.8));let graph='';
 [bottom+span*.12,0,top-span*.12].filter((v,i,arr)=>arr.findIndex(z=>Math.abs(z-v)<1e-6)===i).forEach(v=>{graph+='<line x1="'+pad.l+'" y1="'+y(v)+'" x2="'+(W-pad.r)+'" y2="'+y(v)+'" stroke="'+(v===0?'#91a5a8':'#e2e9e6')+'" stroke-width="'+(v===0?1.4:1)+'"/><text x="'+(pad.l-8)+'" y="'+(y(v)+4)+'" text-anchor="end" font-size="12" fill="#526574">'+esc(nf(v/unit))+'</text>';});
 if(limit!=null){const ly=y(-limit);if(r.peak>limit)graph+='<rect x="'+pad.l+'" y="'+ly+'" width="'+(W-pad.l-pad.r)+'" height="'+Math.max(0,y(-r.peak)-ly)+'" fill="#a13e4c" opacity=".1"/>';graph+='<line class="cash-limit-line" x1="'+pad.l+'" y1="'+ly+'" x2="'+(W-pad.r)+'" y2="'+ly+'"/><text x="'+(W-pad.r)+'" y="'+(ly-6)+'" text-anchor="end" font-size="12" fill="#916322">سقف '+esc(nf(limit/unit))+'</text>';}
 let path='',intraday='';rows.forEach((v,i)=>{const xx=x(v.day);path+=(i?'H'+xx+' V'+y(v.cum):'M'+xx+' '+y(v.cum));intraday+=(i?'H'+xx+' V'+y(-(v.intradayNeed||0)):'M'+xx+' '+y(-(v.intradayNeed||0)));[v.inflow,v.outflow].forEach((value,k)=>{if(!value)return;graph+='<g><title>'+esc('روز '+nf(v.day)+'؛ '+(k===0?'ورود':'خروج')+'؛ '+a.exact(value))+'</title><rect data-cash-direction="'+(k===0?'in':'out')+'" x="'+(xx+(k===0?-barW:1))+'" y="'+Math.min(y(value),y(0))+'" width="'+(barW-1)+'" height="'+Math.max(.7,Math.abs(y(value)-y(0)))+'" rx="2" fill="'+(k===0?'#147467':'#b5606c')+'" opacity=".65"/></g>';});});
 graph+='<path d="'+path+'" fill="none" stroke="#356985" stroke-width="3" stroke-linejoin="round"/>';
 rows.forEach(v=>{graph+='<circle cx="'+x(v.day)+'" cy="'+y(v.cum)+'" r="3" fill="white" stroke="#356985" stroke-width="2"><title>'+esc('روز '+nf(v.day)+'؛ مانده '+a.exact(v.cum))+'</title></circle>'});
 if(r.fundingMode==='intraday')graph+='<path d="'+intraday+'" fill="none" stroke="#a13e4c" stroke-width="1.8" stroke-dasharray="5 4"/>';
 graph+='<circle cx="'+x(r.peakDay)+'" cy="'+y(-r.peak)+'" r="5" fill="#a13e4c"><title>'+esc('اوج نیاز؛ روز '+nf(r.peakDay)+'؛ '+a.exact(r.peak))+'</title></circle>';
 if(r.recoveryDay!=null){const row=rows.find(v=>v.day===r.recoveryDay);graph+='<circle cx="'+x(r.recoveryDay)+'" cy="'+y(row?.cum||0)+'" r="6" fill="#147467"><title>'+esc('آزادسازی کامل؛ روز '+nf(r.recoveryDay))+'</title></circle>';}
 const ticks=rows.length<=4?rows.map(v=>v.day):[first,first+(end-first)/3,first+(end-first)*2/3,end];ticks.forEach(day=>{graph+='<text x="'+x(day)+'" y="'+(H-22)+'" text-anchor="middle" font-size="12" fill="#526574">'+esc('روز '+nf(day,0))+'</text>';});
 box.innerHTML='<div class="chart-unit">واحد محور مبلغ: '+unitName+' · زمان از شروع خرید</div><svg class="cashflow-svg responsive-cash" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="ورود و خروج نقدی و مانده تجمعی؛ منحنی پله‌ای فقط در روزهای واقعی رویداد تغییر می‌کند">'+graph+'</svg><div class="cashflow-legend"><span class="in">ورود نقدی</span><span class="out">خروج نقدی</span><span class="cum">مانده تجمعی</span>'+(r.fundingMode==='intraday'?'<span>خط‌چین: کسری قبل از ورود روز</span>':'')+(limit!=null?'<span>خط طلایی: سقف نقدینگی</span>':'')+'</div>';
}
function render(last){const d=last.d,r=last.r,v=root.TradeEngine.decision(d,r,last);updateContext();const hero=$('resultHero');hero.dataset.status=v.action==='عدم انجام معامله'?'bad':v.action==='انجام معامله'?'good':'warn';$('resultTitle').textContent=v.action;$('resultBadge').textContent='توصیه مدل';$('dealIdentity').textContent=(d.commodity||'معامله')+' · '+nf(d.qTon)+' تن · '+({domestic:'داخلی',import:'واردات',export:'صادرات'}[d.tradeType]);const dims=$('heroSignal').querySelectorAll('.decision-dimension');if(dims[2])dims[2].hidden=true;if(dims[0])dims[0].className='decision-dimension '+(v.executionConfirmed?'good':'warn');
 $('nextActionText').textContent=v.action==='انجام معامله'?'بررسی حدود قیمت و ثبت سناریوی مصوب':v.action==='عدم انجام معامله'?'بررسی اصلاح قیمت و هزینه‌ها پیش از تصمیم مجدد':v.action.includes('قیمت')?'بررسی اثر قیمت پیشنهادی و حفظ حاشیه امن معامله':v.unknownResources.length?'ثبت و تأیید ظرفیت منابع مصرف‌شده':v.cashGap>0||v.facilityGaps.length?'رفع کسری منابع یا بررسی سناریوی حجم کمتر':'بررسی اثر تغییر قیمت و زمان وصول';
 $('decisionNext').innerHTML=(v.action==='انجام معامله'?'مرزهای مجاز معامله':v.action==='عدم انجام معامله'?'بررسی اقتصاد و قیمت':v.action.includes('قیمت')?'بررسی قیمت پیشنهادی':'بررسی آمادگی اجرا')+icon('arrow');
 const metrics=[{label:'سود خالص معامله',value:r.nominal,meta:'پس از هزینه‌ها و زیان مورد انتظار'},{label:'ارزش اقتصادی امروز',value:r.npv,meta:'نرخ تنزیل '+nf(d.hurdle)+'٪ سالانه',tip:'ارزش فعلی خالص (NPV): ارزش امروز پرداخت‌ها و دریافت‌ها با نرخ تنزیل انتخاب‌شده؛ مثبت بودن آن یعنی ایجاد ارزش نسبت به همین انتظار.'},{label:'حاشیه سود خالص',percent:r.profitMargin,meta:r.profitMargin==null?'فروش صفر؛ نسبت قابل محاسبه نیست':r.profitMargin<0?'از هر ۱۰۰ تومان فروش، '+nf(-r.profitMargin*100)+' تومان زیان':'از هر ۱۰۰ تومان فروش، '+nf(r.profitMargin*100)+' تومان سود',tip:'سود خالص معامله تقسیم بر درآمد فروش بدون مالیات قابل بازیافت. این نسبت، بازده سالانه یا بازده سرمایه نیست.'},{label:'اوج نیاز نقدینگی',value:r.peak,meta:r.peak>r.economics.tolerance?'در روز '+nf(r.peakDay,0):'بدون کسری نقدی؛ تعهدات اعتباری جدا کنترل می‌شوند',tip:'بیشترین مبلغی که در طول معامله برای پوشش کسری جریان نقدی باید تأمین شود.'}];
 const kpis=$('resultKpis').children;metrics.forEach((m,i)=>{const k=kpis[i],n=amount(m.value);k.querySelector('.k-label').innerHTML=m.label+(m.tip?'<span class="info-tip" tabindex="0" role="button" title="'+m.tip+'" aria-label="'+m.tip+'" aria-expanded="false">؟</span>':'');k.querySelector('.k-value').innerHTML=i===2?'<bdi>'+pct(m.percent)+'</bdi>':'<bdi>'+n.value+'</bdi><span class="amount-unit">'+n.unit+'</span>';k.classList.toggle('negative',i===2?m.percent!=null&&m.percent<0:m.value<0);k.querySelector('.k-meta').textContent=m.meta;if(i!==2){const exact=document.createElement('span');exact.className='amount-exact';exact.textContent=n.full;k.querySelector('.k-meta').after(exact);}});
 $('resultKpis').querySelectorAll('.info-tip').forEach(n=>{n.onclick=()=>{const old=n.parentElement.querySelector('.tooltip-note');if(old){old.remove();n.setAttribute('aria-expanded','false')}else{const t=document.createElement('span');t.className='tooltip-note';t.textContent=n.title;n.parentElement.append(t);n.setAttribute('aria-expanded','true')}};n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();n.click()}if(e.key==='Escape'){n.parentElement.querySelector('.tooltip-note')?.remove();n.setAttribute('aria-expanded','false')}}});
 const rows=[{key:'cash',name:'نقدینگی',use:r.peak},...['cheque','lc','boe'].map(key=>({key,name:{cheque:'چک',lc:'اعتبار اسنادی',boe:'برات'}[key],use:r.usage[key]}))].filter(x=>x.use>1e-6);$('facilityPanel').innerHTML=rows.length?rows.map(x=>{const lim=d.limits[x.key],ratio=lim==null?null:lim===0?Infinity:x.use/lim*100,c=lim==null?'unknown':ratio>100?'bad':ratio>=80?'warn':'good',need=amount(x.use),cap=amount(lim);return '<div class="resource-row '+c+'"><div class="resource-row-head"><strong>'+x.name+'</strong><span>'+(lim==null?'سقف تأیید نشده':lim===0?'بدون ظرفیت':nf(ratio)+'٪ مصرف')+'</span></div><div class="resource-track" role="img" aria-label="'+x.name+'؛ مصرف '+need.full+'؛ سقف '+(lim==null?'تأیید نشده':cap.full)+'"><span style="width:'+(ratio==null?100:Math.max(0,Math.min(100,ratio)))+'%"></span></div><div class="resource-row-facts"><span>نیاز: <bdi>'+need.value+' '+need.unit+'</bdi></span><span>سقف: <bdi>'+(lim==null?'نامشخص':cap.value+' '+cap.unit)+'</bdi></span></div>'+(lim!=null&&x.use>lim?'<p class="resource-gap">کسری قابل تأمین: '+a.exact(x.use-lim)+'</p>':'')+'</div>';}).join(''):'<div class="empty-state">در الگوی جریان نقدی فعلی، منبعی مصرف نمی‌شود.</div>';
 $('gateSummaryCompact').textContent=$('decisionGates').querySelector('.gate-summary')?.textContent||'';
 const facts=$('cashFlowFacts'),dates=root.TradeEngine.cashMilestones(r),day=v=>v==null?'رویدادی ندارد':'روز '+nf(v,0);
 facts.innerHTML=[['مدت کسری نقدینگی',r.firstFundingDay==null?'بدون کسری':nf(r.duration,0)+' روز'],['پایان کسری نقدینگی',r.firstFundingDay==null?'بدون کسری':r.recoveryDay==null?'تا پایان دوره جبران نشده':day(r.recoveryDay)],['آخرین دریافت وجه',day(dates.lastInflow)],['آخرین پرداخت',day(dates.lastPayment)]].map(x=>'<div class="cash-fact"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('');

 renderCash(last);
 $('freshness').textContent='آخرین محاسبه: '+new Date().toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})+' · نسخه ۱۵';
 if(!$('resultPage').querySelector('.recommendation-boundary'))hero.insertAdjacentHTML('afterend','<p class="recommendation-boundary">توصیه تحلیلی بر اساس ورودی‌های ثبت‌شده؛ تأیید نهایی معامله با مسئول مجاز شرکت است.</p>');
 $('valueBridge').innerHTML=root.EconomicsView.render(r);
}
root.addEventListener('resize',()=>{const last=a.getLast();if(last)renderCash(last)});
return {setup,render};}
root.TradeStudio={create};
})(typeof window==='undefined'?globalThis:window);
