const fs=require('fs'),vm=require('vm'),assert=require('assert'),acorn=require('acorn');
const nodes={},storage={};function el(id){return nodes[id]??={value:'',innerHTML:'',textContent:'',dataset:{},style:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},insertAdjacentHTML(pos,s){this.innerHTML+=s}}}
const ctx={console,setTimeout(){},localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v},document:{getElementById:el}};ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('public/trade-engine.js','utf8'),ctx);vm.runInContext(fs.readFileSync('public/economics-view.js','utf8'),ctx);
const html=fs.readFileSync('public/cockpit.html','utf8'),js=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1];
const body=acorn.parse(js,{ecmaVersion:'latest'}).body[0].expression.callee.body.body,names=body.filter(n=>n.type==='FunctionDeclaration').map(n=>n.id.name);assert.equal(new Set(names).size,names.length,'Duplicate function declarations');
vm.runInContext(js.replace('installV11Inputs();','window.testAPI={setLast:v=>last=v,applySens,renderSensitivity,renderDrivers,riskDrivers,saveDefaults,loadDefaults,renderFinancialDetails,renderCashFlow,renderCompare,state,metricValue,economicDecisionView};return;'),ctx);
const E=ctx.TradeEngine,A=ctx.testAPI,checks=[];function check(name,fn){fn();checks.push(name)}
const base=E.normalize({qTon:100,buyTon:1e6,sellTon:1.2e6,holding:30,hurdle:35,buyCurrency:'TOMAN',sellCurrency:'TOMAN',purchaseVat:10,saleVat:0,serviceVat:10,storage:1000,vatSettlementDay:30,vatRecoveryDay:30,vatCreditMode:'refund',tradeType:'domestic',limits:{cash:0},finLegs:[{method:'cash',share:100}],salesLegs:[{share:100,due:0,markup:0}]});
function set(d){const r=E.simulate(d);A.setLast({d,r,econ:1.1e6,minSell:1.1e6});return r}
check('Zero cash ceiling is not missing',()=>{set(base);const risk=A.riskDrivers().find(x=>x.name==='ریسک نقدینگی');assert(risk.text.includes('صفر'));assert.equal(risk.score,100)});
check('Blank cash ceiling is unrestricted',()=>{set({...base,limits:{cash:null}});assert(A.riskDrivers().find(x=>x.name==='ریسک نقدینگی').text.includes('تعریف نشده'))});
check('VAT accounting effect differs from cash amount',()=>{set(base);A.renderFinancialDetails();let row=el('financialDetails').innerHTML.match(/<tr>[^]*?VAT خرید نقدی[^]*?<\/tr>/)[0];assert(row.includes('۰ تومان'));});
check('All new VAT settings survive save and reload',()=>{const values={purchasePriceIncludesVat:'yes',salePriceIncludesVat:'yes',vatCollectionMode:'custom',vatCollectionDay:'۷۵',vatSettlementDay:'۹۰',vatCreditMode:'refund',vatRecoveryDay:'۱۲۰'};for(let k in values)el(k).value=values[k];A.saveDefaults();for(let k in values)el(k).value='';A.loadDefaults();for(let k in values)assert.equal(el(k).value,values[k]);});
check('Legacy defaults still load',()=>{storage.tdc_v5_clean_defaults=JSON.stringify({hurdle:'۳۵',cash:'۰'});A.loadDefaults();assert.equal(el('hurdleRate').value,'۳۵');assert.equal(el('cashLimit').value,'۰')});
for(const metric of ['npv','nominal','peak','annual'])check('Sensitivity isolates invalid VAT dates: '+metric,()=>{set(base);el('sensX').value='holding';el('sensY').value='sellPrice';el('sensMetric').value=metric;el('sensStepX').dataset.param='holding';el('sensStepX').value='30';el('sensStepY').dataset.param='sellPrice';el('sensStepY').value='5';A.renderSensitivity();assert(el('sensitivityMatrix').innerHTML.includes('قابل محاسبه نیست'));assert.equal((el('sensitivityMatrix').innerHTML.match(/class="sens-cell /g)||[]).length,25);assert(!/NaN|undefined|Infinity/.test(el('sensitivityInsights').innerHTML));});
check('Unavailable period return does not fabricate rankings',()=>{set({...base,sellTon:900000});el('sensMetric').value='annual';A.renderSensitivity();assert(el('driverRanking').innerHTML.includes('قابل محاسبه نیست'))});
check('Comparison uses period return rather than annual value',()=>{A.state.compare=[{name:'test',tradeType:'domestic',qty:100,unit:'ton',funding:'cash',npv:20,nominal:20,peak:100,periodReturn:.2,annualReturn:1.5,efficiency:.2,discountRate:35,ceiling:100,ceilingUnit:'تومان',feasible:true,rec:'buy'}];A.renderCompare();assert(el('compareContent').innerHTML.includes('بازده دوره معامله'));assert(el('compareContent').innerHTML.includes('۲۰٪'));assert(!el('compareContent').innerHTML.includes('۱۵۰٪'))});
check('Same-day funding remains zero',()=>{let r=set(E.normalize({qTon:100,buyTon:1e6,sellTon:1.1e6,holding:30,finLegs:[{method:'lc',share:100,due:30}],salesLegs:[{share:100,due:0}],limits:{}}));A.renderCashFlow(r.events);assert.equal(r.peak,0);assert(!/NaN|Infinity/.test(el('cashFlowChart').innerHTML))});
console.log(JSON.stringify({status:'PASS',checks:checks.length,names:checks},null,2));
