const fs=require('fs'),assert=require('assert');
require('../trade-engine.js');require('../single-sheet-export.js');require('../economics-view.js');
const E=globalThis.TradeEngine,A=globalThis.TradeAudit,base={qTon:100,buyTon:1e6,sellTon:1.2e6,holding:30,hurdle:35,vatRecoveryDay:6000,vatSettlementDay:30,finLegs:[{method:'cash',share:100}],salesLegs:[{share:100,due:0}],limits:{},buyFx:1,sellFx:1};
const buy=(method='lc',feeMode='annual')=>[{method,share:100,due:90,rate:2,costMode:'monthly',fee:1,feeMode,margin:10}];
const sell=(feeMode='annual',markupMode='monthly',method='credit')=>[{method,share:100,due:90,markup:2,markupMode,fee:1,feeMode}];
const cases=[['cash/cash',{}],['cash/90d',{salesLegs:sell()}],['credit/cash',{finLegs:buy()}],['LC/credit',{finLegs:buy(),salesLegs:sell()}],['purchase BOE',{finLegs:buy('boe')}],['purchase cheque',{finLegs:buy('cheque')}],['sale cheque',{salesLegs:sell('annual','monthly','cheque')}],['sale LC',{salesLegs:sell('annual','monthly','lc')}],['mixed sales',{salesLegs:[{share:30,due:0},{share:70,due:90}]}],['customer prepay',{salePrepayPct:20,salePrepayDays:20,salesLegs:sell()}],['supplier advance',{advance:20,finLegs:buy()}],...['flat','monthly','annual'].map(x=>['purchase fee '+x,{finLegs:buy('lc',x)}]),...['flat','monthly','annual'].map(x=>['sale fee '+x,{salesLegs:sell(x)}]),['monthly markup/monthly fee',{salesLegs:sell('monthly')}],['monthly markup/annual fee',{salesLegs:sell('annual')}],['annual markup/flat fee',{salesLegs:sell('flat','annual')}],['VAT',{purchaseVat:10,saleVat:10}],['export VAT credit',{tradeType:'export',purchaseVat:10,insurancePct:1,salesLegs:sell()}],['ECL',{expectedCreditLoss:4,salesLegs:sell()}],['FX import',{tradeType:'import',buyFx:70000,buyTon:7e6,sellTon:9e6,intFreight:2,customsPct:5}],['high profit',{sellTon:3e6}],['near zero',{sellTon:1000000.0001,hurdle:0}],['loss',{sellTon:8e5}],['heavy finance',{finLegs:[{...buy()[0],rate:40}]}],['long collection',{salesLegs:[{share:100,due:3000}]}],['same day daily',{fundingMode:'daily',holding:90,finLegs:buy()}],['same day intraday',{fundingMode:'intraday',holding:90,finLegs:buy()}],['multi tranche',{salePrepayPct:20,salePrepayDays:10,salesLegs:[{method:'cash',share:25,due:0},{...sell()[0],method:'cheque',share:37.5},{...sell('monthly')[0],method:'lc',share:37.5,due:180}]}],['principal fee base',{salesLegs:[{...sell()[0],feeBaseMode:'principal'}]}],['VAT immediate',{purchaseVat:10,saleVat:0,vatCreditTiming:'immediate'}],['VAT writeoff',{purchaseVat:10,saleVat:0,vatCreditMode:'nonrecoverable'}],['empty zero null',{qTon:null,buyTon:'',sellTon:0}],['funding before credit quality',{limits:{cash:0,lc:0},finLegs:buy(),expectedCreditLoss:10}],['tiny expenses',{customCosts:[{name:'tiny',amount:.000001}]}]];
const out=process.argv[2]||'/tmp/release113';fs.mkdirSync(out,{recursive:true});const fd=fs.openSync(out+'/formulas.jsonl','w');const reports=[];
const near=(a,b,label,scale=0)=>assert(Math.abs(a-b)<=Math.max(1e-5,Math.abs(b)*1e-9,scale*1e-10),label+': '+a+' / '+b);
function run(name,patch,keep=false){const d=E.normalize({...base,...patch}),r=E.simulate(d),sum=a=>a.reduce((s,v)=>s+v,0),tol=r.economics.tolerance;
 near(r.nominal,r.saleNetTotal-r.purchaseBase-r.op-r.finCost-r.economics.risk-r.vatWriteOff,'profit');near(r.npv,sum(r.events.map(e=>e.cash/(1+d.hurdle/100)**(e.day/365))),'NPV');near(r.nominal,sum(r.events.map(e=>e.cash)),'cash reconcile',r.saleNetTotal);near(r.npv,r.nominal+r.economics.timeValueEffect,'value bridge',r.saleNetTotal);
 let bal=0,peak=0,cap=0,prev=d.startDay;for(const day of [...new Set(r.events.map(e=>e.day))].sort((a,b)=>a-b)){let events=r.events.filter(e=>e.day===day);cap+=Math.max(0,-bal)*(day-prev);if(d.fundingMode==='intraday')peak=Math.max(peak,-bal-sum(events.map(e=>Math.min(0,e.cash))));bal+=sum(events.map(e=>e.cash));if(d.fundingMode==='daily')peak=Math.max(peak,-bal);prev=day;}near(r.peak,peak,'peak');near(r.capitalDays,cap,'capital days');
 r.salesFinanceLegs.forEach((l,i)=>{const x=d.salesLegs[i],factor=m=>m==='flat'?1:x.due/(m==='monthly'?30:365),principal=r.saleable*d.sellTon/(d.salePriceIncludesVat?1+d.saleVat/100:1)*(1-d.salePrepayPct/100)*x.share/100,markup=principal*(x.markup||0)/100*factor(x.markupMode||'flat');near(l.principal,principal,'sale principal');near(l.markup,markup,'markup');near(l.fee,(x.feeBaseMode==='principal'?principal:principal+markup)*(x.feeIncludesVat?1+d.saleVat/100:1)*x.fee/100*factor(x.feeMode||'annual'),'fee');});
 for(const l of r.financeLegs)near(l.fee,(l.facilityPrincipal+l.financeMarkup)*l.feeRate/100*(l.feeMode==='flat'?1:l.days/(l.feeMode==='monthly'?30:365)),'purchase fee');
 const dec=E.decision(d,r,{econ:d.buyTon*.95});if(r.npv<0)assert.equal(dec.action,'عدم انجام معامله');else if(!r.feasible)assert.equal(dec.action,'اصلاح ساختار تأمین مالی');
 assert(!/NaN|Infinity|undefined/.test(globalThis.EconomicsView.render(r)));const m=A.model(d,r);fs.writeSync(fd,JSON.stringify({name,rows:m.rows})+'\n');
 if(keep){fs.writeFileSync(out+'/'+reports.length+'.json',JSON.stringify(d));reports.push({name,profit:r.nominal,npv:r.npv,peak:r.peak,capitalDays:r.capitalDays,action:dec.action});}
}
cases.forEach(([name,d])=>run(name,d,true));let seed=1132026;const rand=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
for(let i=0;i<3000;i++){let mode=['flat','monthly','annual'][i%3];run('random '+i,{qTon:1+rand()*10000,buyTon:1e5+rand()*1e8,sellTon:1e5+rand()*2e8,holding:Math.floor(rand()*300),hurdle:rand()*80,advance:rand()*70,salePrepayPct:rand()*60,expectedCreditLoss:rand()*15,purchaseVat:i%2?10:0,saleVat:i%2?10:0,serviceVat:10,inbound:rand()*1e4,storage:rand()*1000,tradeType:['domestic','import','export'][i%3],intFreight:rand()*100,insurancePct:1,vatCreditMode:['refund','offset','nonrecoverable'][i%3],fundingMode:i%2?'intraday':'daily',finLegs:[{...buy(['lc','boe','cheque'][i%3],mode)[0],due:Math.floor(rand()*360),rate:rand()*5}],salesLegs:[{...sell(mode)[0],feeBaseMode:i%2?'principal':'receivable',due:Math.floor(rand()*500),feeDirection:i%3?'received':'paid',feeIncludesVat:i%2===0}],limits:i%4?{}:{cash:0}});}
fs.closeSync(fd);fs.writeFileSync(out+'/results.json',JSON.stringify({status:'PASS',deterministic:reports,randomized:3000,seed:1132026},null,2));console.log(JSON.stringify({status:'PASS',deterministic:cases.length,randomized:3000}));
