const assert=require('assert'),fs=require('fs'),vm=require('vm');require('../trade-engine.js');require('../single-sheet-export.js');
const base={tradeType:'domestic',qTon:100,buyTon:1e6,sellTon:1.3e6,holding:30,hurdle:35,vatRecoveryDay:5000,finLegs:[{method:'cash',share:100}],salesLegs:[{share:100,due:90,markup:2,markupMode:'monthly',fee:1,feeMode:'annual',feeDirection:'received'}]};
const near=(a,b)=>assert(Math.abs(a-b)<=Math.max(1e-6,Math.abs(b)*1e-10),`${a} != ${b}`);
const scenarios=[['received annual',{}],['paid annual',{salesLegs:[{...base.salesLegs[0],feeDirection:'paid'}]}],['cash flat',{salesLegs:[{share:100,due:0,markup:0,fee:2,feeMode:'flat'}]}],['cash annual zero',{salesLegs:[{share:100,due:0,fee:2,feeMode:'annual'}]}],['mixed sale',{salePrepayPct:20,salePrepayDays:10,salesLegs:[{share:30,due:0,fee:1,feeMode:'flat'},{share:70,due:120,markup:3,markupMode:'monthly',fee:2,feeIncludesVat:true,feeDirection:'paid',feeTiming:'delivery'}]}],['VAT and ECL',{purchaseVat:10,saleVat:10,expectedCreditLoss:4,badDebtVatTreatment:'recoverable',serviceVat:10,inbound:1000,storage:2000}],['VAT unrecoverable',{purchaseVat:10,saleVat:5,expectedCreditLoss:4,vatCreditMode:'nonrecoverable'}],['import LC',{tradeType:'import',purchaseVat:10,saleVat:10,buyFx:60000,intFreight:1,insurancePct:2,customsPct:3,transferPct:1,finLegs:[{method:'lc',share:100,due:180,rate:3,costMode:'monthly',fee:2,feeMode:'flat',feeFinanced:true,margin:20,vatFinanced:true,chargeVat:true}]}],['export mixed credit',{tradeType:'export',sellFx:60000,intFreight:1,insurancePct:1,transferPct:2,finLegs:[{method:'cheque',share:50,due:90,rate:3},{method:'boe',share:50,due:180,rate:2,fee:2}]}],['zero',{qTon:0}],['loss',{sellTon:800000}],['small profit',{sellTon:1e6+0.0001,salesLegs:[{share:100,due:0,fee:0}]}],['large amounts',{qTon:1e8,buyTon:1e13,sellTon:1.3e13}],['long period',{holding:720,salesLegs:[{...base.salesLegs[0],due:1200}]}],['all custom costs',{customCosts:['fixed_toman','pct_purchase','pct_sale','toman_per_ton','toman_per_kg','toman_per_piece','buyfx_per_ton','sellfx_fixed'].map((type,i)=>({type,amount:0.01,name:type,vat:true,vatRecoverable:i%2===0,quantityBasis:'saleable',timing:'holding'})),pieceKg:5,buyFx:60000,sellFx:70000,serviceVat:10}]];
fs.mkdirSync('/tmp/audit112',{recursive:true});let out=[];
for(const [name,patch] of scenarios){let d={...base,...patch};const r=TradeEngine.simulate(d),m=TradeAudit.model(TradeEngine.normalize(d),r);near(r.nominal,r.economics.revenue-r.economics.totalCosts);near(r.npv,r.events.reduce((a,e)=>a+e.cash/(1+d.hurdle/100)**(e.day/365),0));near(r.nominal,r.events.reduce((a,e)=>a+e.cash,0));assert(r.events.every(e=>e.auditRef));fs.writeFileSync('/tmp/audit112/'+out.length+'.json',JSON.stringify(d));out.push({name,profit:r.nominal,npv:r.npv,feeIncome:r.salesFeeIncome,feeCost:r.salesFeeCost,rows:m.rows.length});}
const r=TradeEngine.simulate(base),principal=130e6,net=principal*(1+.02*90/30),fee=net*.01*90/365;near(r.salesFeeIncome,fee);near(r.nominal,net+fee-100e6);near(TradeEngine.simulate({...base,salesLegs:[{...base.salesLegs[0],feeDirection:'paid'}]}).nominal,net-fee-100e6);
assert.throws(()=>TradeEngine.simulate({...base,salesLegs:[{...base.salesLegs[0],feeDirection:'invalid'}]}));
console.log(JSON.stringify({status:'PASS',scenarios:out},null,2));
