/* Browser regressions. Requires Playwright; APP_CHROMIUM can select an installed Chromium. */
const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{
 const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT||'/tmp/trade13-ui';fs.mkdirSync(out,{recursive:true});
 const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0])==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.woff2')?'font/woff2':f.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(f))}catch(e){res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,...(process.env.APP_CHROMIUM?{executablePath:process.env.APP_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process']}: {})});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:'+server.address().port;
 const fill=async(id,v)=>p.locator('#'+id).fill(String(v));
 const overflow=async()=>p.evaluate(()=>({width:innerWidth,doc:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('.page.active *')].filter(n=>{const r=n.getBoundingClientRect();return r.width>0&&(r.right>innerWidth+1||r.left< -1)}).slice(0,15).map(n=>({tag:n.tagName,id:n.id,cls:n.className,w:n.getBoundingClientRect().width,left:n.getBoundingClientRect().left})),clipped:[...document.querySelectorAll('.page.active .input,.page.active .k-value,.page.active .decision-dimension')].filter(n=>n.getBoundingClientRect().width>0&&n.scrollWidth>n.clientWidth+2).map(n=>n.id||n.className)}));
 await p.goto(url);await p.locator('#introEnter').click();await p.locator('#nextBtn').click();assert(await p.locator('.field-error').isVisible());await p.locator('#commodity').fill('شمش فولادی');for(const [k,v]of Object.entries({quantity:100,purchasePrice:30000000,salePrice:33000000,holdingDays:72,hurdleRate:35}))await fill(k,v);await p.locator('#nextBtn').click();assert(await p.locator('#resourceInputs').isVisible());assert(!await p.locator('#timingAdvanced').isVisible());await p.locator('#nextBtn').click();assert((await p.locator('#heroSignal').innerText()).includes('نیازمند تأیید منابع'));let r=await p.evaluate(()=>window.TDCFINAL.analyze().r);assert.equal(r.nominal,300000000);assert(Math.abs(r.periodReturn-.1)<1e-9);assert(Math.abs(r.profitMargin-1/11)<1e-9);
 await p.locator('.info-tip').first().click();assert(await p.locator('.tooltip-note').isVisible());await p.locator('.info-tip').first().press('Escape');assert.equal(await p.locator('.tooltip-note').count(),0);await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:out+'/desktop.png',fullPage:false});assert.equal((await overflow()).clipped.length,0,JSON.stringify(await overflow()));
 await p.locator('#saveScenarioTop').click();assert.equal(await p.locator('[data-edit]').count(),1);await p.locator('[data-edit="0"]').click();assert((await p.locator('#resultNote').innerText()).includes('تأیید'));await p.locator('#nextBtn').click();await fill('salePrice',36000000);await p.locator('#nextBtn').click();await p.locator('#nextBtn').click();r=await p.evaluate(()=>window.TDCFINAL.analyze().r);assert.equal(r.nominal,600000000);await p.locator('#saveScenarioTop').click();assert.equal(await p.locator('[data-edit]').count(),1);assert((await p.locator('.compare-main').innerText()).includes('تومان'));
 await p.locator('[data-copy="0"]').click();await fill('salePrice',27000000);await p.locator('#nextBtn').click();await fill('cashLimit',4000000000);await p.locator('#nextBtn').click();r=await p.evaluate(()=>window.TDCFINAL.analyze().r);assert.equal(r.nominal,-300000000);assert(r.periodReturn<0);await p.locator('#saveScenarioTop').click();assert.equal(await p.locator('[data-edit]').count(),2);await p.reload();await p.locator('#introEnter').click();await p.locator('#compareOpen').click();assert.equal(await p.locator('[data-edit]').count(),2);await p.locator('[data-edit="0"]').click();assert.equal(await p.locator('#salePrice').inputValue().then(x=>x.replace(/[٬,]/g,'')),'۳۶۰۰۰۰۰۰');
 // Cash/credit transaction: sales fees are connected to the central engine.
 await p.locator('#nextBtn').click();await p.locator('#nextBtn').click();await p.locator('[data-sales="credit"]').click();await fill('saleDue',60);await fill('saleMarkup',2);await p.locator('.sale-fees > summary').click();await fill('salesFee_credit_fee',1);await p.locator('#salesFee_credit_feeMode').selectOption('flat');await p.locator('#salesFee_credit_feeDirection').selectOption('paid');await p.locator('#nextBtn').click();r=await p.evaluate(()=>window.TDCFINAL.analyze().r);assert.equal(r.salesFeeCost,37440000);assert.equal(r.salesFinanceLegs[0].feeRate,1);
 // Mixed sale: no numeric example values, shares/money agree.
 await p.locator('#nextBtn').click();await p.locator('#nextBtn').click();await p.locator('[data-sales="mixed"]').click();assert.equal(await p.locator('[data-k="share"]').first().inputValue(),'');await p.locator('[data-k="share"]').nth(0).fill('40');await p.locator('[data-k="share"]').nth(1).fill('60');await p.locator('[data-k="due"]').fill('30');await p.locator('#nextBtn').click();r=await p.evaluate(()=>window.TDCFINAL.analyze().r);assert.equal(r.salesFinanceLegs.length,2);
 // Cheque heavy finance, mixed parity and amount allocation.
 await p.locator('#nextBtn').click();await p.locator('#nextBtn').click();await p.locator('[data-funding="cheque"]').click();await fill('fsDue',90);await fill('fsRate',20);await fill('fsFee',1.5);await p.locator('#nextBtn').click();r=await p.evaluate(()=>window.TDCFINAL.analyze().r);assert.equal(r.finCost,1845000000);assert(r.nominal<0);
 await p.locator('#nextBtn').click();await p.locator('#nextBtn').click();await p.locator('[data-funding="mixed"]').click();await p.locator('[data-mix="cheque"]').fill('100');r=await p.evaluate(()=>window.TDCFINAL.simulate(window.TDCFINAL.baseData()));assert.equal(r.finCost,1845000000);const amt=p.locator('#fundingMixed .amount-allocation input').nth(1);await amt.fill('3000000000');assert.equal(await p.locator('[data-mix="cheque"]').inputValue(),'۱۰۰');await p.locator('#nextBtn').click();
 // Proposal simulations equal exact engine results and preserve base on apply.
 await p.locator('#proposalResults [data-proposal]').first().click();assert((await p.locator('#compareContent').innerText()).includes('مقایسه با سناریوی مبنا'));await p.locator('[data-edit]').last().click();
 // Responsive layouts and large values: no body overflow at four mobile/tablet widths.
 for(const width of [360,390,768,1440]){await p.setViewportSize({width,height:900});const o=await overflow();await p.screenshot({path:out+'/check-'+width+'.png'});assert(o.doc<=o.width+1,JSON.stringify(o));assert.equal(o.clipped.length,0,JSON.stringify(o));await p.screenshot({path:out+'/results-'+width+'.png'});}
 await p.setViewportSize({width:1440,height:1000});await p.locator('#printReport').click();await p.emulateMedia({media:'print'});await p.pdf({path:out+'/management-report.pdf',preferCSSPageSize:true});assert.equal((fs.readFileSync(out+'/management-report.pdf').toString('latin1').match(/\/Type\s*\/Page\b/g)||[]).length,1);await p.emulateMedia({media:'screen'});
 const download=p.waitForEvent('download');await p.locator('#exportExcel').click();await (await download).saveAs(out+'/trade-audit.xlsx');
 await p.locator('#nextBtn').click();await fill('quantity',1000000);await fill('purchasePrice',300000000000);await fill('salePrice',310000000000);await p.locator('#nextBtn').click();await p.locator('#nextBtn').click();for(const width of [360,1440]){await p.setViewportSize({width,height:900});const o=await overflow();await p.screenshot({path:out+'/check-'+width+'.png'});assert(o.doc<=o.width+1,JSON.stringify(o));assert.equal(o.clipped.length,0,JSON.stringify(o));}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks:['unknown funding not approved','fee integration','scenario edit/copy/persistence','mixed share and amount','proposal preserve/compare','responsive 360/390/768/1440','large amounts','PDF and Excel downloads'],out}));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
