/* Visual, accessibility and financial reconciliation scenarios. Requires Playwright and axe-core. */
const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.QA_OUTPUT||'/tmp/trade14-visual');fs.mkdirSync(out,{recursive:true});const server=http.createServer((req,res)=>{const f=path.join(root,req.url.split('?')[0]==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.woff2')?'font/woff2':f.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(f))}catch(e){res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.APP_CHROMIUM?{executablePath:process.env.APP_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process']}: {})});const p=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port);await p.locator('#introEnter').click();await p.waitForTimeout(550);await p.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const checks=[];
const axe=async(name)=>{const v=await p.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(x=>({id:x.id,impact:x.impact,nodes:x.nodes.map(n=>n.target)}))});checks.push({name,violations:v});};
await axe('entry');
const fill=async(data)=>{for(const [id,v]of Object.entries(data))await p.locator('#'+id).fill(String(v))};
await fill({commodity:'شمش فولادی',quantity:100,purchasePrice:30000000,salePrice:33000000,holdingDays:72,hurdleRate:35});await p.locator('#nextBtn').click();await p.locator('#cashLimit').fill('4000000000');await p.screenshot({path:out+'/finance.png'});await axe('finance');await p.locator('#nextBtn').click();await axe('result');await p.locator('#cashFlowChart').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/cash-desktop.png'});assert(await p.locator('.responsive-cash').count());assert((await p.locator('.responsive-cash path').first().getAttribute('d')).includes('H'));
const cases=[{name:'high-profit',sale:60000000},{name:'low-profit',sale:30010000},{name:'loss',sale:27000000},{name:'tiny-components',sale:33000000,ops:.000001},{name:'heavy-finance',sale:33000000,finance:true}];let results=[];
for(const c of cases){await p.locator('#nextBtn').click();await fill({salePrice:c.sale});await p.locator('#nextBtn').click();await fill({inboundCost:c.ops||0});if(c.finance){await p.locator('[data-funding="cheque"]').click();await fill({fsDue:90,fsRate:20,fsFee:1.5});await p.locator('#chequeLimit').fill('6000000000');}else await p.locator('[data-funding="cash"]').click();await p.locator('#nextBtn').click();const r=await p.evaluate(()=>TDCFINAL.analyze().r);assert(Math.abs(r.economics.reconciliationDifference)<=r.economics.tolerance);assert(Number.isFinite(r.npv));assert.equal(await p.locator('.value-waterfall').count(),1);assert.equal(await p.locator('#valueBridge [role="alert"]').count(),0);results.push({name:c.name,profit:r.nominal,npv:r.npv,margin:r.profitMargin,finance:r.finCost});await p.locator('#valueBridge').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/'+c.name+'.png'});}
await p.setViewportSize({width:360,height:900});await p.evaluate(()=>scrollTo(0,0));await axe('mobile-result');await p.locator('#valueBridge').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/mobile-bridge.png'});await p.locator('#cashFlowChart').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/mobile-cash.png'});assert(await p.locator('.bridge-mobile').isVisible());assert.equal(await p.locator('.waterfall-scroll').isVisible(),false);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
for(const width of [360,390,680,768,1024,1440,1920]){await p.setViewportSize({width,height:1000});await p.locator('#nextBtn').click();await p.screenshot({path:out+'/entry-'+width+'.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('#nextBtn').click();await p.screenshot({path:out+'/finance-'+width+'.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('#nextBtn').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
await p.locator('#saveScenarioTop').click();await axe('compare');
// Import/export UI branches preserve field availability and responsive layout.
await p.locator('[data-edit="0"]').click();await p.locator('#nextBtn').click();for(const type of ['import','export']){await p.locator('[data-trade="'+type+'"]').click();await fill(type==='import'?{purchaseFx:60000,purchasePrice:500,salePrice:33000000}:{saleFx:60000,salePrice:550,purchasePrice:30000000});assert(await p.locator('#foreignSection').isVisible());await p.screenshot({path:out+'/foreign-'+type+'.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
assert.deepEqual(errors,[]);assert(checks.every(c=>c.violations.length===0),JSON.stringify(checks));fs.writeFileSync(out+'/verification.json',JSON.stringify({results,accessibility:checks,errors},null,2));console.log(JSON.stringify({results,accessibility:checks,errors}));await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
