function render(){
 const t=topicEl.value,s=subEl.value,chart=document.getElementById('chart');let insights=[],signal='تحلیل عرضه و تقاضا';
 if(t==='group'){const ds=s==='up'?P.slide1Upstream:P.slide1Downstream;setMeta(s==='up'?'ظرفیت زنجیره بالادست گروه':'ظرفیت زنجیره پایین‌دست گروه','مقایسه ظرفیت اسمی وضعیت فعلی با افق ۱۴۱۰','میلیون تن','گروه فولاد مبارکه','فعلی ↔ ۱۴۱۰',ds.categories.length);chart.innerHTML=compareChart(ds);insights=['مقایسه همزمان ظرفیت فعلی و افق ۱۴۱۰، محل تمرکز توسعه ظرفیت در حلقه‌های زنجیره را روشن می‌کند.','اختلاف دو وضعیت، مبنای ورود به تحلیل موازنه و فرصت‌های بازرگانی در سناریوهای بعدی است.'];signal='رشد ظرفیت و تغییر ساختار زنجیره';}
 else if(t==='main'){const ds=s==='core'?P.slide2MainCompany:P.slide3MainCompanyDownstream;const ps=s==='core'?['گندله','آهن اسفنجی','اسلب','ورق گرم']:['ورق نورد سرد','ورق گالوانیزه','ورق رنگی','ورق قلع اندود'];const unit=s==='core'?'میلیون تن':'هزار تن';setMeta('عملکرد شرکت اصلی فولاد مبارکه','مقایسه تولید، خودمصرفی و موازنه در ۱۴۰۴ و ۱۴۰۵',unit,'شرکت فولاد مبارکه','۱۴۰۴ ↔ ۱۴۰۵',ps.length);chart.innerHTML=mainCompany(ds,ps,unit);insights=P.insights.mainCompany;signal='فرصت تأمین، تجارت و ریسک ورق';}
 else if(t==='groupfuture'){if(s==='18'){setMeta('سناریو تولید ۱۸ میلیون تن فولاد میانی','عرضه، تقاضا و موازنه آتی حلقه‌های بالادست','میلیون تن','گروه فولاد مبارکه','افق ۱۴۱۰',5);chart.innerHTML=supplyDemand(P.slide4Group18Mt);insights=['در سناریوی هدف ۱۸ میلیون تن، فشار تقاضا در حلقه‌های ابتدایی زنجیره به‌ویژه سنگ‌آهن برجسته می‌شود.'];signal='شکاف ظرفیت در سناریوی رشد';}else if(s==='util'){setMeta('تولید بر اساس نرخ بهره‌وری فعلی','پیش‌بینی عرضه و تقاضای درون‌حلقه‌ای','میلیون تن','گروه فولاد مبارکه','افق ۱۴۱۰',5);chart.innerHTML=supplyDemand(P.slide5GroupUtilization);insights=P.insights.groupUtilization;signal='فرصت معدن و بازرگانی داخلی';}else{setMeta('ظرفیت پایین‌دست و خودمصرفی','کلاف گرم و اسلب در حالت ظرفیت اسمی','میلیون تن','گروه فولاد مبارکه','افق ۱۴۱۰',2);chart.innerHTML='<div class="product-cards"><article class="product-card"><h3>کلاف گرم</h3>'+metricCards(P.slide6HotCoil)+'</article><article class="product-card"><h3>اسلب</h3>'+metricCards(P.slide6Slab)+'</article></div>';insights=['در ظرفیت اسمی، مازاد بالقوه اسلب و کلاف گرم باید در کنار تقاضای واقعی بازار تفسیر شود.'];signal='مازاد بالقوه پایین‌دست';}}
 else if(t==='country'){if(s==='capacity'){setMeta('موازنه کشور بر پایه ظرفیت اسمی','سناریوی ۱ تولید آتی زنجیره بالادست','میلیون تن','بازار کشور','افق ۱۴۰۷',5);const fake={categories:P.slide7CountryCapacity.categories,series:[{name:'عرضه',values:[150,100.91107,92.75,74.67,64.7763]},{name:'تقاضا',values:[180.69,84.0642894,80.061228,55.47624,null]},{name:'موازنه',values:[-30.69,16.8467806,12.688772,19.19376,null]}]};chart.innerHTML=supplyDemand(fake);insights=P.insights.countryCapacity;signal='کسری معدن، مازاد حلقه‌های بعدی';}else if(s==='energy'){setMeta('سناریوی محدودیت انرژی','تولید بر اساس بهره‌وری گذشته با محدودیت تأمین انرژی','میلیون تن','بازار کشور','افق ۱۴۰۷',4);chart.innerHTML=supplyDemand(P.slide8Energy);insights=P.insights.countryEnergy;signal='اثر انرژی بر عرضه زنجیره';}else if(s==='ore'){setMeta('سناریوی محدودیت عرضه سنگ‌آهن','زنجیره تولید با سقف ۱۲۵ میلیون تن سنگ‌آهن داخلی','میلیون تن','بازار کشور','افق ۱۴۰۷',5);chart.innerHTML=oreFlow();insights=P.insights.countryOre;signal='محدودیت ماده اولیه و افت بهره‌وری';}else{setMeta('سناریوی ۴: حالت محتمل','میانگین وزنی سه وضعیت عرضه و بهره‌وری','میلیون تن','بازار کشور','افق ۱۴۰۷',5);chart.innerHTML=likelyView();insights=P.insights.countryLikely;signal='سناریوی مرجع تصمیم‌گیری';}}
 else if(t==='slab'){const ds=s==='capacity'?P.slide12SlabCapacity:P.slide12SlabLikely;setMeta('بازار اسلب کشور',s==='capacity'?'تولید بر اساس ظرفیت اسمی':'سناریوی محتمل بر اساس پیش‌بینی تقاضای بازار','میلیون تن','بازار اسلب','افق ۱۴۱۰',3);chart.innerHTML=composition(ds,'اسلب');insights=P.insights.slab;signal='ظرفیت سرمایه‌گذاری و تجارت خارجی';}
 else if(t==='hot'){setMeta('بازار کلاف گرم کشور','ظرفیت اسمی، تقاضا و مازاد عرضه','میلیون تن','بازار کلاف گرم','افق ۱۴۱۰',3);chart.innerHTML=composition(P.slide13HotCoil,'کلاف گرم');insights=P.insights.hotCoil;signal='مازاد عرضه و تهدید زنجیره توزیع';}
 else{setMeta('روند تجارت و صادرات محصولات فولادی','داده تاریخی صادرات به تفکیک محصول','هزار تن','تجارت خارجی','۱۳۹۸ تا ۱۴۰۴',DATA.tradeRows.length);chart.innerHTML=tradeView();insights=['روند صادرات، لایه مکمل تحلیل موازنه است و نشان می‌دهد مازاد بالقوه هر محصول تا چه حد سابقه جذب در بازار خارجی داشته است.'];signal='ظرفیت واقعی تجارت خارجی';}
 setInsights(insights,signal);
}
setSubs();